name: grocery_app
description: A Flutter app for grocery shopping

dependencies:
  flutter:
    sdk: flutter
  get_x: ^4.0.2
  shared_preferences: ^2.0.8
  connectivity_plus: ^1.6.5
  cached_network_image: ^3.0.0
  material_design_3: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
